# Generated by Django 3.0.3 on 2020-02-24 12:00

from django.db import migrations

def forwards_func(apps, schema_editor):
    pro_cat_model = apps.get_model("mainapp", "ProductCategory")  
    pro_model = apps.get_model("mainapp", "Product")  
    con_model = apps.get_model("mainapp", "Contacts")  

    pro_cat_obj = pro_cat_model.objects.create(
        pk=1,
        name="дом", description="Дизайнерская мебель для дома")

    pro_model.objects.create(
        pk=1,
        category=pro_cat_obj,  
        name="Стул",
        image="products_images/product-4.jpg",
        short_desc="Стул повышенного качества",
        description="Максимально комфортный стул. Сочетание стиля и качества.",
        price="2150.5",
        quantity=8,
    )
    pro_model.objects.create(
        pk=2,
        category=pro_cat_obj,
        name="Стул повышенного качества",
        image="products_images/product-21.jpg",
        short_desc="Комфортный стул повышенного качества",
        description="Комфортный стул повышенного качества. Сочетание стиля и качественных материалов. Не оставит равнодушным самого искушенного ценителя комфорта.",
        price="5990.9",
        quantity=6,
    )
    pro_model.objects.create(
        pk=3,
        category=pro_cat_obj,  
        name="Часы настенные",
        image="products_images/product-4-sm.jpg",
        short_desc="Стильные настенные часы",
        description="Стильные часы для  дома и офиса. Обладают повышенным запасом хода. Сочетание качества материалов и дизайна.",
        price="7560.6",
        quantity=11,
    )
    del pro_cat_obj  

    pro_cat_obj = pro_cat_model.objects.create(
        pk=2,
        name="офис", description="Офисная мебель от лучших дизайнеров"
    )

    pro_model.objects.create(
        pk=4,
        category=pro_cat_obj,  
        name="Лампа",
        image="products_images/product-5-sm.jpg",
        short_desc="Стильная лампа",
        description="Офисная лампа в стиле HI-TECK. Впишется в интерьер любого офисного помещения",
        price="8760.7",
        quantity=9,
    )
    pro_model.objects.create(
        pk=5,
        category=pro_cat_obj,  
        name="Офисный диван",
        image="products_images/product-3-sm.jpg",
        short_desc="Стильный офисный диван",
        description="Удобный стильный офисный диван. Впишется в интерьер  практически любого офиса.",
        price="21990.9",
        quantity=3,
    )
    del pro_cat_obj 

    pro_cat_obj = pro_cat_model.objects.create(
        pk=3,
        name="модерн", description="Стиль модер не оставит никого равнодушным"
    )
    del pro_cat_obj  

    pro_cat_obj = pro_cat_model.objects.create(
        pk=4,
        name="классика", description="Классический стиль для любого интерьера"
    )
    
    
    con_model.objects.create(
        pk=1,
        city="Москва",
        phone="+7-888-888-8888", 
        email="info@geekshop.ru", 
        address="В пределах МКАД"
    )
    con_model.objects.create(
        pk=2,
        city="Екатеринбург",
        phone="+7-777-777-7777",
        email="info_yekaterinburg@geekshop.ru",
        address="Близко к центру",
    )
    con_model.objects.create(
        pk=3,
        city="Владивосток",
        phone="+7-999-999-9999",
        email="info_vladivostok@geekshop.ru",
        address="Близко к океану",
    )


def reverse_func(apps, schema_editor):
    pro_cat_model = apps.get_model("mainapp", "ProductCategory")  
    con_model = apps.get_model("mainapp", "Contacts")  

    pro_cat_model.objects.all().delete()
    con_model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
