# Generated by Django 3.0.3 on 2020-02-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='город')),
                ('phone', models.PositiveIntegerField(unique=True, verbose_name='телефон')),
                ('email', models.CharField(max_length=128, unique=True, verbose_name='электронная почта')),
                ('address', models.TextField(verbose_name='адрес')),
            ],
        ),
    ]
