# Generated by Django 3.0.3 on 2020-02-17 21:58

from django.conf import settings
from django.db import migrations

def forwards_func(apps, schema_editor):
    if settings.DEBUG:

        try:
            from authnapp.models import ShopUser

            ShopUser.objects.create_superuser(
                "admin", "root@google.com", "admin", age=33
            )
        except:
            print("Cann't create super user for debug")


def reverse_func(apps, schema_editor):
    if settings.DEBUG:
        # Only in DEBUG mode!
        try:
            from authnapp.models import ShopUser

            ShopUser.objects.create_superuser(
                "admin", "root@google.com", "admin", age=33
            )
        except:
            print("Cann't delete super user for debug")


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0001_initial'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
